// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfXtr0ybxh71A4thnkZdis63QkfmUrgdU',
    appId: '1:1065907360298:web:d56219a8e58a869be12953',
    messagingSenderId: '1065907360298',
    projectId: 'crisisconnect-youngminds',
    authDomain: 'crisisconnect-youngminds.firebaseapp.com',
    storageBucket: 'crisisconnect-youngminds.appspot.com',
    measurementId: 'G-Q31CZLEK3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARpl27imTQapM1qbNsOnJqRa69OUXklAE',
    appId: '1:1065907360298:android:918123aed6c17baae12953',
    messagingSenderId: '1065907360298',
    projectId: 'crisisconnect-youngminds',
    storageBucket: 'crisisconnect-youngminds.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx8D-rQlTaQdzB1FM30z97ZWvj42sb9O4',
    appId: '1:1065907360298:ios:60ff666944c2b002e12953',
    messagingSenderId: '1065907360298',
    projectId: 'crisisconnect-youngminds',
    storageBucket: 'crisisconnect-youngminds.appspot.com',
    iosBundleId: 'com.example.crisisconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx8D-rQlTaQdzB1FM30z97ZWvj42sb9O4',
    appId: '1:1065907360298:ios:60ff666944c2b002e12953',
    messagingSenderId: '1065907360298',
    projectId: 'crisisconnect-youngminds',
    storageBucket: 'crisisconnect-youngminds.appspot.com',
    iosBundleId: 'com.example.crisisconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfXtr0ybxh71A4thnkZdis63QkfmUrgdU',
    appId: '1:1065907360298:web:d462dbc03dd0d654e12953',
    messagingSenderId: '1065907360298',
    projectId: 'crisisconnect-youngminds',
    authDomain: 'crisisconnect-youngminds.firebaseapp.com',
    storageBucket: 'crisisconnect-youngminds.appspot.com',
    measurementId: 'G-B7N95NXPPT',
  );

}